---
language: node_js
node_js:
  - 6
  - 8
  - 9
cache:
  yarn: true
  apt: true
  directories:
  - node_modules
  - vendor
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-6
      - clang
      - libicu-dev
env:
  global:
    - TMPDIR=/tmp
    - PRETTIER_SWIFT_SWIFTC=vendor/swiftc
install:
  - yarn install
  - scripts/ci/download
script:
  - yarn lint
  - AST_COMPARE=1 yarn test -- --runInBand
