---
language: node_js
node_js:
  - 6
  - 8
  - 9
cache:
  yarn: true
  directories:
  - node_modules
  - vendor
install:
  - yarn install
  - scripts/ci/download
script:
  - yarn lint
  - SWIFTC=vendor/swiftc AST_COMPARE=1 yarn test -- --runInBand
