---
language: node_js
node_js:
  - 6
  - 8
  - 9
cache:
  yarn: true
  apt: true
  directories:
  - node_modules
  - vendor
addons:
  apt:
    packages:
      - clang
      - libicu-dev
env:
  global:
    - TMPDIR=/tmp
    - PRETTIER_SWIFT_SWIFTC=vendor/swiftc
install:
  - yarn install
  - scripts/ci/download
  - vendor/swiftc --version
script:
  - yarn lint
  - yarn test -- --runInBand
